apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: junaidp/titanic-fast-api:latest  # Use your Docker image
        ports:
        - containerPort: 80  # Assuming FastAPI listens on port 80
        env:
        - name: ENVIRONMENT
          value: "production"

